<a href="https://colab.research.google.com/github/beyounding/data_processing/blob/main/eeg_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from pandas import read_excel as read

In [ ]:
from sklearn import preprocessing
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.ensemble import VotingClassifier
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from matplotlib import pyplot as plt

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
label_encoder = preprocessing.LabelEncoder()

In [ ]:
path='/content/merge12.xlsx'
data = read(path)
data

time  freq           Fp1       Fp2        F7        F3        Fz  \
0     0.000     3  4.409600e+12  0.360943  0.325448  1.345075  1.651437   
1     0.015     3  9.209339e+12  0.237087  0.949976  0.963214  1.593962   
2     0.030     3  2.032911e+13  0.395083  1.526684  1.569937  0.985665   
3     0.045     3  2.424447e+13  0.892350  1.244912  3.859368  0.977293   
4     0.060     3  1.528867e+13  1.111415  0.727207  5.266611  2.166351   
...     ...   ...           ...       ...       ...       ...       ...   
1085  1.560    31  6.210006e+12  1.864840  0.053837  0.175751  0.159288   
1086  1.575    31  7.272504e+12  2.726824  0.277070  0.037900  0.353579   
1087  1.590    31  7.238309e+12  3.402845  0.681088  0.402483  1.027176   
1088  1.605    31  6.307300e+12  3.276735  0.943497  0.717874  1.545387   
1089  1.620    31  4.742765e+12  2.441693  0.885731  0.704362  1.509883   

            F4        F8        T3  ...        P3        Pz        P4  \
0     0.394474  0.795999  0.079237  ...  3.287380  1.479211  1.525952   
1     1.124909  0.538387  0.213164  ...  5.497775  3.800277  1.447126   
2     1.742142  0.533974  0.298531  ...  4.758530  5.036044  0.914571   
3     1.391103  1.338679  0.225813  ...  2.982624  3.440304  1.382249   
4     0.844436  2.272418  0.244880  ...  4.978165  2.655656  2.737322   
...        ...       ...       ...  ...       ...       ...       ...   
1085  0.164702  0.379771  0.039071  ...  1.790559  1.466299  1.739232   
1086  0.369496  0.564706  0.505752  ...  1.423617  1.027070  1.603714   
1087  0.627200  0.626470  1.204189  ...  0.903122  0.553120  1.134276   
1088  0.785009  0.519180  1.649264  ...  0.483334  0.244421  0.651307   
1089  0.750706  0.330039  1.600710  ...  0.241961  0.119956  0.320893   

            T6        O1        O2        A1        A2       Ref  trial  
0     1.068929  0.331825  0.112707  0.590307  1.026125  0.433435      1  
1     2.380626  0.347356  0.179102  0.629849  1.050265  0.767174      1  
2     2.690443  0.832657  0.138594  1.529468  2.860370  1.913949      1  
3     1.754501  1.307489  0.045366  2.285696  5.429465  2.691442      1  
4     2.260328  1.148942  0.010598  1.715654  5.495535  2.013804      1  
...        ...       ...       ...       ...       ...       ...    ...  
1085  0.458364  0.230294  3.015674  3.512388  3.768509  2.110473      2  
1086  0.003420  0.485244  1.794045  3.079061  2.210451  0.716540      2  
1087  0.564247  0.869908  0.704617  2.415877  1.012840  0.373804      2  
1088  1.730435  1.077581  0.147244  1.792046  0.434912  0.982115      2  
1089  2.686794  0.962358  0.009309  1.285683  0.286004  1.644147      2  

[1090 rows x 25 columns]

In [ ]:
x = data.values[::, 2:24]
label_encoder.fit(data["trial"])
y = label_encoder.transform(data["trial"])

In [ ]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size = 0.3)

In [ ]:
x_train = StandardScaler().fit_transform(x_train)
x_test = StandardScaler().fit_transform(x_test)

In [ ]:
#importance
model = ExtraTreesClassifier()
model.fit(x, y)
print(model.feature_importances_)

[0.01646764 0.02461652 0.02374902 0.02719328 0.02097763 0.08586097
 0.04228683 0.06430787 0.09768096 0.03711008 0.05442056 0.03602178
 0.09960738 0.06322216 0.06854086 0.01990205 0.02502336 0.02194036
 0.0251981  0.03003825 0.06843695 0.04739739]


In [ ]:
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
pred_dt = dt.predict(x_test)

print(metrics.accuracy_score(y_test, pred_dt)*100)
print(confusion_matrix(y_test, pred_dt))
print(classification_report(y_test, pred_dt))

89.60244648318043
[[151  20]
 [ 14 142]]
              precision    recall  f1-score   support

           0       0.92      0.88      0.90       171
           1       0.88      0.91      0.89       156

    accuracy                           0.90       327
   macro avg       0.90      0.90      0.90       327
weighted avg       0.90      0.90      0.90       327



In [ ]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
pred_rf = rf.predict(x_test)

print(metrics.accuracy_score(y_test, pred_rf)*100)
print(confusion_matrix(y_test, pred_rf))
print(classification_report(y_test, pred_rf))

99.08256880733946
[[170   1]
 [  2 154]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       171
           1       0.99      0.99      0.99       156

    accuracy                           0.99       327
   macro avg       0.99      0.99      0.99       327
weighted avg       0.99      0.99      0.99       327



In [ ]:
nb = GaussianNB()
nb.fit(x_train, y_train)
pred_nb = nb.predict(x_test)
print(metrics.accuracy_score(y_test, pred_nb)*100)
print(confusion_matrix(y_test, pred_nb))
print(classification_report(y_test, pred_nb))

85.01529051987767
[[171   0]
 [ 49 107]]
              precision    recall  f1-score   support

           0       0.78      1.00      0.87       171
           1       1.00      0.69      0.81       156

    accuracy                           0.85       327
   macro avg       0.89      0.84      0.84       327
weighted avg       0.88      0.85      0.85       327



In [ ]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
pred_lr = lr.predict(x_test)
print(metrics.accuracy_score(y_test, pred_lr)*100)
print(confusion_matrix(y_test, pred_lr))
print(classification_report(y_test, pred_lr))


94.80122324159022
[[160  11]
 [  6 150]]
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       171
           1       0.93      0.96      0.95       156

    accuracy                           0.95       327
   macro avg       0.95      0.95      0.95       327
weighted avg       0.95      0.95      0.95       327



In [ ]:
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
pred_knn = knn.predict(x_test)
print(metrics.accuracy_score(y_test, pred_knn)*100)
print(confusion_matrix(y_test, pred_knn))
print(classification_report(y_test, pred_knn))

99.08256880733946
[[169   2]
 [  1 155]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       171
           1       0.99      0.99      0.99       156

    accuracy                           0.99       327
   macro avg       0.99      0.99      0.99       327
weighted avg       0.99      0.99      0.99       327



In [ ]:
nn = MLPClassifier(hidden_layer_sizes =(200, 200, 200), activation = 'relu', max_iter = 100)
nn.fit(x_train, y_train)
pred_nn = dt.predict(x_test)

print(metrics.accuracy_score(y_test, pred_nn)*100)
print(confusion_matrix(y_test, pred_nn))
print(classification_report(y_test, pred_nn))

89.60244648318043
[[151  20]
 [ 14 142]]
              precision    recall  f1-score   support

           0       0.92      0.88      0.90       171
           1       0.88      0.91      0.89       156

    accuracy                           0.90       327
   macro avg       0.90      0.90      0.90       327
weighted avg       0.90      0.90      0.90       327



In [ ]:
gb = GradientBoostingClassifier()
gb.fit(x_train, y_train)
pred_gb = gb.predict(x_test)

print(metrics.accuracy_score(y_test, pred_gb)*100)
print(confusion_matrix(y_test, pred_gb))
print(classification_report(y_test, pred_gb))

98.1651376146789
[[165   6]
 [  0 156]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       171
           1       0.96      1.00      0.98       156

    accuracy                           0.98       327
   macro avg       0.98      0.98      0.98       327
weighted avg       0.98      0.98      0.98       327

